### ISSUE TITLE
Can VueResourceType.Remote save the actual file name instead of the date/time stamp?

### ISSUE THREAD

**Issue by justinmulligan** [pratikksahu/JetPDFVue#3]
Is there a way to save the name of the PDF files that been pulled using VueResourceType.Remote?
I would like to download once using VueResourceType.Remote then load using VueResourceType.Local from then on if thats possible? 

If VueResourceType.Remote can save the file using a name I specify rather then a date/time stamp, then i can do a if file.exists()

**Comment by pratikksahu** [comment]
`val vueFilePicker = rememberSaveable(saver = VueFilePicker.Saver) {
        VueFilePicker()
    }
val launcher = vueFilePicker.getLauncher(
        interceptResult = {
        //Perform file operation on imported file
        },
        onResult = {
            //Get the final file
        }
    )`

You can intercept the result and save the file.
